### ISSUE TITLE
Command failed: git commit -a -m ci: version bump to v0.0.1

### ISSUE THREAD

**Issue by MagicLegend** [phips28/gh-action-bump-version#126]
I've tried running a workflow including this Action, but it fails for some reason. This is really my first time playing with Github Actions, so I probably messed up on some syntax somewhere. Shame they don't have the syntax validator like Bitbucket CI...

Regardless, the error:

```
Run phips28/gh-action-bump-version@master
/usr/bin/docker run --name c179d982a28fa7ec43a7aa872ed2e9296901_4c23a7 --label 48c179 --workdir /github/workspace --rm  -e GITHUB_TOKEN -e PACKAGEJSON_DIR -e INPUT_TAG-PREFIX -e INPUT_MINOR-WORDING -e INPUT_MAJOR-WORDING -e INPUT_PATCH-WORDING -e INPUT_RC-WORDING -e INPUT_SKIP-TAG -e INPUT_PACKAGEJSON_DIR -e INPUT_TARGET-BRANCH -e INPUT_DEFAULT -e INPUT_PREID -e INPUT_COMMIT-MESSAGE -e INPUT_PUSH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Repo-Name/Repo-Name":"/github/workspace" 48c179:d982a28fa7ec43a7aa872ed2e9296901
commit messages: [ 'TICKET-123 - Added node runtime to workflow\nundefined' ]
config words: {
  majorWords: [ 'BREAKING CHANGE', 'major' ],
  minorWords: [ 'feat', 'minor' ],
  patchWords: null,
  preReleaseWords: [ 'pre-alpha', 'pre-beta', 'pre-rc' ]
}
version action after first waterfall: patch
version action after final decision: patch
currentBranch: master
current: 0.0.0 / version: patch
✖  fatal     Error: Command failed: git commit -a -m ci: version bump to v0.0.1 

On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

    at makeError (/node_modules/execa/index.js:174:9)
    at /node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /index.js:148:5
✖  fatal     Failed to bump version
```

Used `master.yml`:
```
name: RedactedCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Create Release Folder
      run: |
        mkdir -p release/folder
        rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' vendor/packages/* ./release/vendor

    - name: Create M2 Release Folder
      run: |
        mkdir -p release/magento2/app/code/Vendor
        rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' app/code/Vendor/* ./release/magento2/app/code/Vendor

    - name: Get variables
      run: |
        echo "VENDORFOLDER=$(find release/vendor/* -type d -prune -printf '%f\n')" >> $GITHUB_ENV
        echo "VENDORPATH=$(find release/vendor/* -type d -prune -print)" >> $GITHUB_ENV
        echo "M2FOLDER=$(find release/magento2/app/code/Vendor/* -type d -prune -printf '%f\n')" >> $GITHUB_ENV

    - name: 'Setup Node.js'
      uses: 'actions/setup-node@v1'
      with:
        node-version: 14

    - name: 'Automated Version Bump'
      uses: 'phips28/gh-action-bump-version@master'
      id: version-bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGEJSON_DIR: ${{ env.VENDORPATH }}
      with:
        tag-prefix: 'v'

    - name: 'Verify tag'
      run: |
        echo "TAG=${{ steps.version-bump.outputs.newTag }}" >> $GITHUB_ENV
        echo "New tag: ${{ env.TAG }}""

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ env.TAG }}
        tag_name: ${{ env.TAG }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Zip artifacts
      run: |
        zip -r release/${{ env.VENDORFOLDER }}-v${{ env.TAG }}-fe.zip
        zip -r release/${{ env.M2FOLDER }}-v${{ env.TAG }}-be.zip

    - name: Switch to Release Folder
      run: |
        cd release
        ls -la

    - name: Upload FE Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/${{ env.VENDORFOLDER }}-v${{ env.TAG }}-fe.zip
        asset_name: ${{ env.VENDORFOLDER }}-v${{ env.TAG }}-fe.zip
        asset_content_type: application/zip

    - name: Upload BE Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/${{ env.M2FOLDER }}-v${{ env.TAG }}-be.zip
        asset_name: ${{ env.M2FOLDER }}-v${{ env.TAG }}-be.zip
        asset_content_type: application/zip
```
