### ISSUE TITLE
Multiple bump version

### ISSUE THREAD

**Issue by arryanggaputra** [phips28/gh-action-bump-version#136]
Hi Phips, thank you so much for these GitHub actions, it help me a lot 🔥 . Anyway, is it possible to bump multiple package.json in a single run? What I did now is

```
      - name: 'Automated Version Bump Project'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip-tag: 'true'

      - name: 'Automated Version Bump For library'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'libs/lightstrap'
        with:
          skip-tag: 'true'
 ```

This will create two commits, do you have any suggestions for me about this?

Thank you phips 🙏🏻
