### ISSUE TITLE
Manually set version type in workflow definition

### ISSUE THREAD

**Issue by Brainicism** [phips28/gh-action-bump-version#140]
Not sure if I missed part of the documentation, but it'd be cool if there was something like 'version-type' that we could specify in a workflow, to give some human intervention for determining what type of version bump is required.

My use case would be something like this. I have a 'dev' branch that I push commits to frequently. Occasionally, I'll deploy my 'dev' branch by pushing all of the changes to 'master' and executing some code on a remote server to pull in the latest changes and restart the application. What I'm envisioning is that my GH Action could take in a parameter, [major/minor/patch], that gets passed into the workflow, and consumed by the 'Automated Version Bump' step. 

Something like:
```
name: deploy-prod

on:
  workflow_dispatch:
  inputs:
      version-type:
        description: 'The automated version bump type. One of [major, minor, patch]'     
        required: true
        default: 'patch'
...
   steps:
     - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type:  ${{ github.event.inputs.version-type}}
```
