### ISSUE TITLE
Support for mono repos

### ISSUE THREAD

**Issue by darklight9811** [phips28/gh-action-bump-version#150]
Would like to request support for mono repositories.

**Comment by phips28** [comment]
whats your structure?
do you have one package.json in the root to determine the version for multiple packages?
or do you want to bump the version in multiple folders?

**Comment by darklight9811** [comment]
@phips28 I'm using rushjs, in case you want to see the [repo](https://github.com/AcaiJS/modules). I want to bump in multiple folders.

**Comment by phips28** [comment]
ok, you could use this action multiple times in a row, and set that `PACKAGEJSON_DIR`. Also set the `skip-push: true`. (checkout the docs)
And then do the set tag + push on the last entry.
Do you know what I mean?

**Comment by Nekoo36** [comment]
> And then do the set tag + push on the last entry.

@phips28  Could you explain a bit more about this?

**Comment by phips28** [comment]
you add multiple entries for this action in your action file with the `PACKAGEJSON_DIR` and `skip-push: true`. 
And on the last action entry, you do not skip-push. therefore the last action run will commit and push everything the prev actions did

**Comment by Nekoo36** [comment]
@phips28 I am getting a bit confused for the last action, which PACKAGEJSON_DIR should be set in this step?

**Comment by phips28** [comment]
Basically the last package.json dir, you want to bump.

Can you share your action.yml?

**Comment by Nekoo36** [comment]
> Basically the last package.json dir, you want to bump.

@phips28 it's working as expected now. You saved my day, thanks a lot!

**Comment by phips28** [comment]
@Nekoo36 glad I could help you :) 
Maybe you can post your action code snippet for other user who are looking for such setup. Thank you ;)

**Comment by Nekoo36** [comment]
Sure :）
```
name: 'Bump Version'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'packages/test1/**'
      - 'packages/test2/**'

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'Set path filter'
        uses: dorny/paths-filter@v2
        id: path-filter
        with:
          filters: |
            test1:
              - 'packages/test1/**'
            test2:
              - 'packages/test2/**'
      - name: 'Bump version for test1'
        id: test1-version
        if: steps.path-filter.outputs.test1 == 'true'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'test1-v'
          skip-push: ${{ steps.path-filter.outputs.test2 }}
          default: prerelease
          major-wording: 'MAJOR, BREAKING CHANGE'
          minor-wording: 'minor'
          patch-wording: 'feat'
          rc-wording: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'packages/test1'
      - name: 'Bump version for test2'
        id: test2-version
        if: steps.path-filter.outputs.test2 == 'true'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'test2-v'
          default: prerelease
          major-wording: 'MAJOR, BREAKING CHANGE'
          minor-wording: 'minor'
          patch-wording: 'feat, fix'
          rc-wording: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'packages/test2'


```
