### ISSUE TITLE
Warning: Unexpected input(s) 'bump-policy'

### ISSUE THREAD

**Issue by yonatanaftali** [phips28/gh-action-bump-version#155]
Using the bump-policy option, I'm getting the following error during run-time:
`Warning: Unexpected input(s) 'bump-policy', valid inputs are ['tag-prefix', 'minor-wording', 'major-wording', 'patch-wording', 'rc-wording', 'skip-tag', 'PACKAGEJSON_DIR', 'target-branch', 'default', 'preid', 'commit-message', 'push']`

This is my configuration:
```
      - name: Bump Version
        uses: phips28/gh-action-bump-version@v9.0.1
        with:
          minor-wording: MinorBump
          major-wording: MajorBump
          preid: alpha
          skip-tag: true
          commit-message: 'bump version => {{version}}'
          target-branch: preAlphas/preAlpha-${{ steps.today.outputs.date }}
          bump-policy: 'ignore'
```
