### ISSUE TITLE
Getting Error: package.json could not be found in your project's root when using custom `package.json` path configuration

### ISSUE THREAD

**Issue by ugreg** [phips28/gh-action-bump-version#162]
Getting error `(node:1857) UnhandledPromiseRejectionWarning: Error: package.json could not be found in your project's root.` when using [custom package json path](https://github.com/marketplace/actions/automated-version-bump#packagejson_dir) configuration.

```yml
    - name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      with:
        PACKAGEJSON_DIR: 'www_themade_org'
```

![image](https://user-images.githubusercontent.com/8151045/167335681-e1a6fff2-f03f-4f9d-8f09-da34b61280a0.png)
