### ISSUE TITLE
gh-action-bump-version runs non-stop

### ISSUE THREAD

**Issue by fayssal-kb** [phips28/gh-action-bump-version#164]
Hello !

Thanks for this github action, I have one problem with that.

I am using this action in my github workflows as bellow with `actions/checkout@v2`,  to automate bump version of nodejs application with Qasar

 ```
    - name: Automated Version Bump
      uses: "phips28/gh-action-bump-version@v9.0.16"
      with:
        tag-prefix: ''
        commit-message: 'CI: bumps version to {{version}}'
        target-branch: 'master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
the job in which I use this action, the step `Automated Version Bump` runs non-stop for at least 5 minutes and I have to stop it manually.
