### ISSUE TITLE
auto bump fails if PR

### ISSUE THREAD

**Issue by oc-stephen-bennett** [phips28/gh-action-bump-version#173]
If you set branch protection on master to force PR, you can get action-bump-version to work via adding a bypass required pull requests user.

But if you require a status check to run an action on PR, when the PR is approved, it tries to run the status check again on the auto-bump tags / package.json upgrade. Even though its using the bypass user.

**Comment by Inshaal93** [comment]
[This](https://github.com/phips28/gh-action-bump-version/issues/62) solved it for me

**Comment by oc-stephen-bennett** [comment]
Hey, 

Still sadly not working for me :( my  push action:

```
name: Push

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: 'actions/checkout@v2'
        with:
          token: ${{ secrets.BYPASS }}
          persist-credentials: false
          fetch-depth: 50

      - name: Automated Version Bump
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.BYPASS }}
        with:
          skip-tag: 'false'
```

i have a PR action like: 

```
name: Pull Request

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
```

i have pre-commit added to the require branches to be up to date before merging - status checks

![image](https://user-images.githubusercontent.com/100411569/181208193-78727765-edf6-4f22-a9ec-0ae077541fcb.png)


I get the error: 

![image](https://user-images.githubusercontent.com/100411569/181207986-075e04a1-8c73-4058-9f9a-4e8b052bfe31.png)
