### ISSUE TITLE
How to get the new version output for the next step?

### ISSUE THREAD

**Issue by sebastiangug** [phips28/gh-action-bump-version#174]
Currently have the following step: 

```
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        id: version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: "main"
          commit-message: "CI: bumps version to {{version}} [skip ci]"
          major-wording: "MAJOR"
          patch-wording: "patch,fix"
          default: minor
``` 

but  steps.version_bump.outputs.newVersion and `steps.version_bump.outputs.version` are both undefined
