### ISSUE TITLE
Commit ahead after push bump version

### ISSUE THREAD

**Issue by mdeoliveira-hw** [phips28/gh-action-bump-version#179]
I wanted to add a job who publish package at the end of bump job. But when the bump ended, we have a branch that 1 commit ahead. I tried to add a sleep after bump job to prevent time of push, but it does not resolve the issue.

Has anyone encountered this problem as well ? And did you have an idea on how to fix that ?

Result of a job with commit ahead : [https://github.com/mdeoliveira-hw/gh-push-protected/actions/runs/3061249516/jobs/4940784425](https://github.com/mdeoliveira-hw/gh-push-protected/actions/runs/3061249516/jobs/4940784425)

Workflow to reproduce : 

```yaml
on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Bump package version
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
          commit-message: "CI: bumps version to {{version}} [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Ahead commits
        run: git rev-list --left-right main...@{upstream}
```
