### ISSUE TITLE
Error: spawn npm ENOENT

### ISSUE THREAD

**Issue by Rutger-Knijnenburg** [phips28/gh-action-bump-version#193]
I'm using this action to version bump after building the project and installing NPM packages.

However on the version bump action I get this error. I don't understand why, the runner is using node V 16.13.1.

```
✖  fatal     Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
✖  fatal     Failed to bump version
```

My folder structure:

Root
---- ProjectA [folder]
------- dist [folder
------- readme.md
------- package.json
------- package-lock.json
---- ProjectB [folder
.gitignore
.readme

Action (partly):

```
    - name: "Version Bump"
      uses: "phips28/gh-action-bump-version@master"
      with:
        tag-prefix: 'V'
        minor-wording:  'minor,Minor'
        major-wording: 'major,Major'
        rc-wording: 'release, RELEASE,Release, Alpha,alpha'
        commit-message: 'CI: bumps version to {{version}} [skip ci]'
      env:
        PACKAGEJSON_DIR:  'ProjectA'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
