### ISSUE TITLE
default: prerelease and preid not working

### ISSUE THREAD

**Issue by abhineetsbhamra** [phips28/gh-action-bump-version#200]
I am using this below config in my workflow yaml
```
      - name: Set the preid
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Automated Version Bump
        id: version-update
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.some_secret }}
        with:
          skip-tag: 'true'
          default: prerelease
          bump-policy: all
          preid: ${{ steps.vars.outputs.sha_short }}
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          minor-wording: 'MINOR'
          major-wording: 'MAJOR'
          patch-wording: 'PATCH'
```

now the problem is that `default: prerelease` is not being honoured and i get. reply from action like below (No version keywords found, skipping bump.) My commit message dosnt have any special words. IMO the default action of bumping prerelease should take effect. https://github.com/phips28/gh-action-bump-version#preid

```
Run phips28/gh-action-bump-version@master
  with:
    skip-tag: true
    default: prerelease
    bump-policy: all
    preid: [2](https://github.com/Wesfarmers-Digital/cdk-constructs/actions/runs/3644168693/jobs/6153139137#step:6:2)09[7](https://github.com/Wesfarmers-Digital/cdk-constructs/actions/runs/3644168693/jobs/6153139137#step:6:7)fb8
    commit-message: CI: bumps version to {{version}} [skip ci]
    minor-wording: MINOR
    major-wording: MAJOR
    patch-wording: PATCH
    rc-wording: pre-alpha,pre-beta,pre-rc
    skip-commit: false
    skip-push: false
    push: true
  env:
    NPM_CONFIG_USERCONFIG: /opt/actions-runner/_work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    GITHUB_TOKEN: ***
process.env.GITHUB_WORKSPACE /opt/actions-runner/_work/cdk-constructs/cdk-constructs
tagPrefix: 
tagSuffix: 
commit messages: [ '[OP-77[9](https://github.com/Wesfarmers-Digital/cdk-constructs/actions/runs/3644168693/jobs/6153139137#step:6:9)0] updated the side branch yaml\nundefined' ]
config words: {
  majorWords: [ 'MAJOR' ],
  minorWords: [ 'MINOR' ],
  patchWords: [ 'PATCH' ],
  preReleaseWords: [ 'pre-alpha', 'pre-beta', 'pre-rc' ]
}
version action after first waterfall: prerelease
version action after final decision: null
✔  success   No version keywords found, skipping bump.
```
