### ISSUE TITLE
PR Title no longer used?

### ISSUE THREAD

**Issue by CWSites** [phips28/gh-action-bump-version#202]
Hey @phips28, up until a couple months ago I was able to specify which version to bump using the PR title. I noticed the last few weeks that it is no longer using that. I looked through your documentation and it says the wording looks in the commit message, but that's not something I have control to edit when I merge into `master`.

Is there a particular reason this changed or a version I can point back to so I can continue using it this way? I have a pull request with the title `MINOR Release` and it's doing a patch update. 

### Screenshot of past releases that have been successful
![Screenshot 2022-12-09 at 4 50 30 PM](https://user-images.githubusercontent.com/1242102/206801615-0d243d87-8341-494f-8f78-b715c63f8a4e.png)

### My current configuration
```
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # checkout SHA which includes the changelog
        ref: '${{ steps.changelog-sha.outputs.long_sha }}'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PACKAGEJSON_DIR: 'libs/dot-components'
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          # default: prerelease
          major-wording: 'MAJOR'
          minor-wording: 'MINOR'
          ## Providing patch-wording will override commits defaulting to a patch bump.
          # patch-wording: 'patch'
          ## rc-wording will override the 'preid'
          # rc-wording: 'alpha, RELEASE, BETA'
          target-branch: 'master'
          preid: 'alpha'
```

### Log Output

```
with:
    commit-message: CI: bumps version to {{version}} [skip ci]
    major-wording: MAJOR
    minor-wording: MINOR
    target-branch: master
    preid: alpha
    rc-wording: pre-alpha,pre-beta,pre-rc
    skip-tag: false
    skip-commit: false
    skip-push: false
    default: patch
    bump-policy: all
    push: true
  env:
    GITHUB_TOKEN: ***
    PACKAGEJSON_DIR: libs/dot-components
Couldn't find any commits in this event, incrementing patch version...
tagPrefix: 
commit messages: []
config words: {
  majorWords: [ 'MAJOR' ],
  minorWords: [ 'MINOR' ],
  patchWords: null,
  preReleaseWords: [ 'pre-alpha', 'pre-beta', 'pre-rc' ]
}
version action after first waterfall: patch
version action after final decision: patch
currentBranch: master
current 1: 2.0.2 / version: patch
newVersion 1: 2.0.[3](https://github.com/digital-ai/dot-components/actions/runs/3662308908/jobs/6191374539#step:4:3)
current 2: 2.0.2 / version: patch
execute npm version now with the new version: patch
newVersion 2: 2.0.3
newVersion after merging tagPrefix+newVersion: 2.0.3
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-[10](https://github.com/digital-ai/dot-components/actions/runs/3662308908/jobs/6191374539#step:4:10)-[11](https://github.com/digital-ai/dot-components/actions/runs/3662308908/jobs/6191374539#step:4:11)-github-actions-deprecating-save-state-and-set-output-commands/
git commit failed because you are using "actions/checkout@v2"; but that doesnt matter because you dont need that git commit, thats only for "actions/checkout@v1"
✔  success   Version bumped!
```
