### ISSUE TITLE
How to get trigger GH workflows from Automated Version Bump

### ISSUE THREAD

**Issue by a-Leong** [phips28/gh-action-bump-version#203]
I'd like to have a separate deploy workflow triggered by the version bump commit.

This is my version bump action
```yaml
name: 'Bump package.json version on merge'
on:
    push:
        branches:
            - 'main'

jobs:
    bump-version:
        name: 'Bump Version on main'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: 'phips28/gh-action-bump-version@master'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  target-branch: 'main'
                  major-wording: 'MAJOR,Major,major'
                  minor-wording: 'MINOR,Minor,minor,FEAT,Feat,feat'
```

This is the workflow I'd like triggered
```yaml
name: Build and Deploy Web App on New Version
on:
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    build_and_deploy:
        # Run job when Automated Version Bump increments package version or workflow is manually dispatched
        if: ${{ github.actor == 'Automated Version Bump' || github.event_name == 'workflow_dispatch' }}

        runs-on: ubuntu-latest

        # ...

```

However commits pushed to main by Automated Version Bump are apparently not detected by the second workflow. There's no [ci skip] in the message, and the workflow isn't skipped by the if expression in the build_and_deploy job, it isn't run at all. I have also tried
```yaml
on:
  push:
    tags:
      - '*'
```
with the same result.

Is this something that can be acheived with a different gh-action-bump-version config? Or am I not seeing another issue all together?
