### ISSUE TITLE
Couldn't find any commits in this event [...]

### ISSUE THREAD

**Issue by migbash** [phips28/gh-action-bump-version#208]
Having an issue of:

```
Couldn't find any commits in this event, incrementing patch version...
tagPrefix: v
tagSuffix: 
commit messages: []
```

when trying to run an `action` on:

```
on:
  pull_request:
    types:
      - closed
    branches:
      - main
 
jobs:
  build:
    if: github.event.pull_request.merged == true
    [....]
 ```

---

Is there a reason it is not detecting the `event` / `commit` ?

**Comment by phips28** [comment]
Hi,
do I understand this correctly: you want to run the action when you merge your PR?
If so, whats your merge strategy? And does it generate a commit? (Merge, squash)

**Comment by migbash** [comment]
Hi @phips28,

Yes, that's exactly what I mean.

> If so, whats your merge strategy?

Using `squash` merge, which is closed with a `squash merge commit`.

**Comment by phips28** [comment]
Hmm. There are no commit messages in your logs. 
can you try `push` instead of `pull_request` action on your main branch?
Just for testing?
But other than that I cant really help here. Never had this setup you have.

**Comment by Barokai** [comment]
i have the same problem when using this action with pull_request [opened], any chance to fix this (or introduce this functionality)?

Goal would be to bump the version when a PR to main is created.

current workflow:
```yml
name: Auto-bump version on PR

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  bump-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTO_BUMP }}

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_USER: "xxx"
          GITHUB_EMAIL: "xxx"
          GITHUB_TOKEN: ${{ secrets.AUTO_BUMP }}
        with:
          default: patch
          skip-tag: "true"
          commit-message: 'CI: bump version to {{version}} [skip ci]'
          minor-wording: "#minor"
          major-wording: "#major"
          patch-wording: "#patch"
```
