### ISSUE TITLE
Issue if the main branch is locked

### ISSUE THREAD

**Issue by botmaster** [phips28/gh-action-bump-version#213]
Hello,
Thank you for this great job.

Everything works fine unless I protect my main branch 😕

```
name: 'Bump Version'

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v9.1.4
        with:
          tag-prefix: 'v'
          patch-wording:  'fix, patch' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
```
How to make it work on a locked branch ?

Thanks
