### ISSUE TITLE
Support hotfixes ("post-releases")

### ISSUE THREAD

**Issue by MartinCura** [phips28/gh-action-bump-version#222]
Thank you for this useful tool!

I was wondering if this could support hotfixes in some way. We currently have the following as part of our CI `release` pipeline:

```yaml
      # On branch `main`, bump according to commit message
      - name: Bump version, commit, tag (according to commit message)
        if: "${{ github.ref_name == 'main' }}"
        uses: phips28/gh-action-bump-version@v10.0.1
        with:
          tag-prefix: "v"
          minor-wording: "add,Adds,new,minor,feat"
          # patch-wording: "fix,patch,bug"
          # Beginning with 'ci:' will prevent infinite loop
          commit-message: "ci: Release {{version}}\n\n${{ steps.changelog.outputs.changelog }}"
          skip-push: "true"

      # On special branch `deploy_hotfix`, bump hotfix version
      - name: Bump version, commit, tag (for hotfix)
        if: "${{ github.ref_name == 'deploy_hotfix' }}"
        uses: phips28/gh-action-bump-version@v10.0.1
        with:
          tag-prefix: "v"
          version-type: "prerelease"
          preid: "hotfix"
          # Beginning with 'ci:' will prevent infinite loop
          commit-message: "ci: Release hotfix {{version}}"
          skip-push: "true"
```

This does mostly what we want, but the _patch_ is bumped too because the hotfix is actually treated as a pre-release of the next patch version.

Ideally we could have one of the following:
- `v1.2.3` is bumped to `v1.2.3-hotfix.0`, or
- `v1.2.3` is bumped to `v1.2.3.1`, or something else similar to this.

Is there a way we could achieve something closer to this?

Semver itself doesn't seem to support this kind of branching off for "special" releases, but there's several discussions on it, such as https://github.com/semver/semver/issues/241, and i feel it's something kind of lacking in the spec.

As i'm writing this maybe this is an issue for https://github.com/npm/node-semver 🤔 

Lastly, another way of doing it is just bumping the version ourselves and maybe use this Action only for the other actions. How could we skip the automatic bump in this case, but still get the tag and release?
