### ISSUE TITLE
Bumps minor or major instead of patch

### ISSUE THREAD

**Issue by lukaspanni** [phips28/gh-action-bump-version#228]
I use this action on multiple repositories with this simple configuration:
```yaml
- name:  'Automated Version Bump'
  uses:  'phips28/gh-action-bump-version@master'
  env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    tag-prefix: 'v'
```

As you can see in this commit history (https://github.com/lukaspanni/cordova-multiconfig/commits/main) it will sometimes bump the minor or even major version after a commit that does not contain any of the documented keywords.
I noticed this behavior when using dependabot to update dependencies to the next minor/major version, see screenshots below.
Do you have any suggestions to get rid of that behavior?

![grafik](https://github.com/phips28/gh-action-bump-version/assets/16417093/8a33aaf1-ff68-427e-b75e-292a3f5b3ff7)
![grafik](https://github.com/phips28/gh-action-bump-version/assets/16417093/dff14604-ba7a-45de-bad7-92275e1542df)
