### ISSUE TITLE
Error: Invalid format '├── https://github.com/sponsors/broofa'

### ISSUE THREAD

**Issue by sernaferna** [phips28/gh-action-bump-version#237]
Getting the error listed above at the tail end of execution.  The entire job seems to be running successfully (i.e. there is a message that says "✔  success   Version bumped!"), but then there is an error about being unable to process file command 'output' successfully.

Full log:

```
process.env.GITHUB_WORKSPACE /home/runner/work/<appname>/<appname>/apps/<msname>
tagPrefix: 
tagSuffix: 
commit messages: [
  'force build\nundefined',
  'Merge pull request #1348 from sernaferna/bnd\n\nforce build\nundefined'
]
config words: {
  majorWords: [ 'MAJOR' ],
  minorWords: [ 'MINOR' ],
  patchWords: null,
  preReleaseWords: [ 'pre-alpha', 'pre-beta', 'pre-rc' ]
}
version action after first waterfall: patch
version action after final decision: patch
runInWorkspace | command: git args: [ 'config', 'user.name', '"Automated Version Bump"' ]
runInWorkspace | command: git args: [
  'config',
  'user.email',
  '"gh-action-bump-version@users.noreply.github.com"'
]
currentBranch: main
runInWorkspace | command: npm args: [
  'version',
  '--allow-same-version=true',
  '--git-tag-version=false',
  '6.1.5'
]
current 1: 6.1.5 / version: patch
newVersion 1:   run `npm fund` for details
runInWorkspace | command: git args: [
  'commit',
  '-a',
  '-m',
  'ci: version bump to   run `npm fund` for details'
]
runInWorkspace | command: git args: [ 'checkout', 'main' ]
runInWorkspace | command: npm args: [
  'version',
  '--allow-same-version=true',
  '--git-tag-version=false',
  '6.1.5'
]
current 2: 6.1.5 / version: patch
execute npm version now with the new version: patch
newVersion 2:   run `npm fund` for details
newVersion after merging tagPrefix+newVersion+tagSuffix:   run `npm fund` for details
runInWorkspace | command: sh args: [
  '-c',
  'echo "newTag=  run `npm fund` for details" >> $GITHUB_OUTPUT'
]
runInWorkspace | command: git args: [
  'commit',
  '-a',
  '-m',
  'ci: version bump to   run `npm fund` for details'
]
git commit failed because you are using "actions/checkout@v2" or later; but that doesnt matter because you dont need that git commit, thats only for "actions/checkout@v1"
runInWorkspace | command: git args: [
  'push',
  '***github.com/sernaferna/<appname>.git'
]
✔  success   Version bumped!
##[error]Unable to process file command 'output' successfully.
##[error]Invalid format '├── https://github.com/sponsors/broofa'
```

*There is an error about a git commit failing, too, but I don't* think *that's causing the problem -- I could be wrong.*

This is for a smaller microservice within a larger monorepo; the relevant section of the YAML is:

```yaml
  bump-versions:
    needs: paths-filter
    name: Bump version numbers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Bump version for <msname>
        uses: phips28/gh-action-bump-version@master
        if: ${{ needs.paths-filter.outputs.msname == 'true' }}
        with:
          target-branch: 'main'
          skip-tag: 'true'
          major-wording: 'MAJOR'
          minor-wording: 'MINOR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'apps/msname'
          GITHUB_REF: ${{ github.ref}}

      - name: Bump version for Workspace
        uses: phips28/gh-action-bump-version@master
        with:
          target-branch: 'main'
          major-wording: 'MAJOR'
          minor-wording: 'MINOR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ github.ref}}
```
