### ISSUE TITLE
Output the new tag

### ISSUE THREAD

**Issue by abouroubi** [phips28/gh-action-bump-version#24]
Is there a way to output the created tag ?
I need to use it in another action to create a new release with the created tag

**Comment by phips28** [comment]
Not sure if/how that works.

lg, Phil

**Comment by abouroubi** [comment]
With the offcial Actions sdk, you can do something like this : 
`core.setOutput("output_name", my_variable)`

But the "actions-toolkit" don't seem to expose them

**Comment by abouroubi** [comment]
I have made a PR to the "actions-toolkit", it has been merged, now there is an ouptut object that we cas set, I'll make a PR as soon as the new version of "actions-toolkit" will be available.

**Comment by aangelinsf** [comment]
@abouroubi, I'm looking at the releases and it's been a long time:
https://github.com/actions/toolkit/releases

Do you see a way to get that new release accelerated? Getting the version from the action would be best rather than reading it from the package.json file.

**Comment by abouroubi** [comment]
It's not the official toolkit that's used by this action, but this one : https://github.com/JasonEtco/actions-toolkit/releases

They just released a new version with my changes included, but it also has some other breaking changes, so updating will take more time than expected.

I'll see if I have the time to update it.

**Comment by aangelinsf** [comment]
Ah, ok.

**Comment by aangelinsf** [comment]
In the meantime, we're using the following:

```
`VERSION=`cat package.json | jq -r .version`
echo $VERSION`
```

**Comment by leezng** [comment]
Is there any new development here?

**Comment by phips28** [comment]
@abouroubi have you had time to implement this?

**Comment by abouroubi** [comment]
@phips28 unfortunately no, I didn't have the time to implement it.

**Comment by saul-gush** [comment]
I am looking to do this too.

If the code knows what the bump or tag number is, you should be able to expose that and reference in subsequent step:

${{ steps.<id>.outputs.<value> }}

Here is an example:
https://github.community/t/how-to-get-just-the-tag-name/16241/11

export in one step
```
- name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
```

use in later step
```
- name: Build base image
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
```

**Comment by saul-gush** [comment]
This is how I got it to work - hope it helps

```
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v8.0.5
        with:
          tag-prefix: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Export TAG Parameter
        id: tag_name
        run: |
          echo ::set-output name=TAG::`cat package.json | jq -r .version`
        shell: bash
```

Later on send a notification about the new version
```
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          overwrite: "{title: `NPM update: - ${{github.repository}} | ${{ steps.tag_name.outputs.TAG }}` }"
```
