### ISSUE TITLE
Anything that can be done to improve performance?

### ISSUE THREAD

**Issue by sernaferna** [phips28/gh-action-bump-version#244]
I hate to even ask this question. 🙂 I love this action; it's a core part of my build pipeline. But *because* it is, I'm wondering if there's anything that can be done to improve performance? 

I'm using it for an NPM Workspace with up to 8 separate apps that may or may not need to get their version numbers updated (depending what changed in the code). The  way I've managed to get it working:

1. Use a job for `dorny/paths-filter` to find which apps have changed
2. Use a job with multiple steps for `phips28/gh-action-bump-version`
    1. One step for each app that may have been updated (with an `if` to check if it's actually changed, and with `skip-tag` turned on)
    2. One overall step to update the version for the entire workspace (regardless of any other changes, and with `skip-tag` off)
3. Continue with jobs for building/deploying each app that has changed

With each of those steps happening in sequence, the more changes there have been made, the longer that job takes to run. (Could be as little as a minute or as long as 3+ minutes.)

I've tried bump-version as separate jobs, in parallel, instead of steps within one job, but then the commits fail as they try overwriting each other. (Or rather, the _first_ one that happens to get committed succeeds and then the rest fail.)

```
error: failed to push some refs to 'https://github.com/repo/repo.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by phips28** [comment]
Hi @sernaferna, the action runs for about ~15-20sec as you can see here: https://github.com/phips28/gh-action-bump-version/actions
pretty fast I would say 😉  

did you measure your single steps (like with console logs) to find the longest running actions? maybe its another action that spins up an extra instance.

**Comment by sernaferna** [comment]
Thanks for your quick response, @phips28 -- much appreciated.

I've gone back through the history of my builds and I'm seeing something similar, the job takes ~15 seconds to run pretty consistently -- *except* for the first execution, which usually takes around a minute. So I guess there's some initialization that needs to happen the first time it runs -- which is probably out of your control? (In which case this issue should be closed.)

For an extreme test I made a change that caused each of my apps to get updated (technically it's 5 apps and 3 libraries, but same diff in this case); therefore the action had to run for each one. The timings I got were as follows, but as mentioned, I've looked back through the history and seen similar timings:

* App 1: **1m 4s**
* App 2: **15s**
* App 3: **15s**
* App 4: **15s**
* App 5: **15s**
* Lib 1: **16s**
* Lib 2: **15s**
* Lib 3: **15s**
* Workspace (with `skip-tag` turned off): **3s**

As you can see, the ~15-20 second timing is absolutely correct and consistent, except for that first execution. (And the last! Only 3 seconds!) In cases where only a couple of the apps are modified it's still consistent: the first time the action runs it's a bit over a minute, subsequent runs are ~15s, and the final Workspace update (which always executes) is 3-4s.

For reference, my job looks like this:

```yaml
  bump-versions:
    needs: paths-filter # previous job that determined which apps/libs are changed
    name: Bump version numbers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Bump version for App 1
        uses: 'phips28/gh-action-bump-version@master'
        if: ${{ needs.paths-filter.outputs.appone== 'true' }}
        with:
          target-branch: 'main'
          skip-tag: 'true'
          major-wording: 'MAJOR'
          minor-wording: 'MINOR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'apps/appone'
          GITHUB_REF: ${{ github.ref}}

      - name: Bump version for App 2
        uses: 'phips28/gh-action-bump-version@master'
        if: ${{ needs.paths-filter.outputs.app2 == 'true' }}
        with:
          target-branch: 'main'
          skip-tag: 'true'
          major-wording: 'MAJOR'
          minor-wording: 'MINOR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'apps/app2'
          GITHUB_REF: ${{ github.ref}}

      # 6 more steps like this

      - name: Bump version for Workspace
        uses: 'phips28/gh-action-bump-version@master'
        with:
          target-branch: 'main'
          major-wording: 'MAJOR'
          minor-wording: 'MINOR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ github.ref}}
```

I don't know if it's turning off the `skip-tag` option, or turning off the `PACKAGEJSON_DIR` option, but setting the version for the overall workspace is lightning fast. 🙂
