### ISSUE TITLE
Doesn't work with PR massages 

### ISSUE THREAD

**Issue by alonapester** [phips28/gh-action-bump-version#254]
Hello,
I am trying to create a workflow that will bump version every time I close a PR and merge it to master, the problem is that it doesn't fine my commit (I am using squash commit for the merge if that matters).
I does tag but It won't use any of my massages:

My workflow:
```
name: Bump version

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  bump-app-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    env:
      github.event.head_commit.message: ${{ github.event.pull_request.title }}
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: '0'

      
    - name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        major-wording:  '#major'
        minor-wording:  '#minor'
        patch-wording:  '#patch'
        target-branch: master
        tag-prefix:  'v'
        commit-message: 'CI: bumps version to {{version}}'
```

The logs:
```
Couldn't find any commits in this event, incrementing patch version...
tagPrefix: v
tagSuffix: 
commit messages: []
```

I would love to get some help with this.

Thank you,
Alon
