### ISSUE TITLE
Usage with Deploy Keys / SSH

### ISSUE THREAD

**Issue by brunolemos** [phips28/gh-action-bump-version#260]
I'm trying to bypass the branch protection rules (https://github.com/phips28/gh-action-bump-version/issues/156) by using a Deploy Key. But it seems that gh-action-bump-version is not using the same auth as the checkout. Any suggestions?

```yml
steps:
  - uses: actions/checkout@v4
    with:
      ref: refs/heads/dev
      ssh-key: ${{ secrets.DEPLOY_KEY }} # Private ssh key
      persist-credentials: true # <<-- Does this expose a token to GITHUB_TOKEN?
  - id: bump-package-version
    uses: 'phips28/gh-action-bump-version@master'
    with:
      commit-message: 'CI: bumps version to {{version}} [skip ci]'
      default: 'minor'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Tried with or without this line; how to use the ssh auth?
      PACKAGEJSON_DIR: packages/editor
```

### Rulesets

"Deploy keys" bypass the branch protection rule

<img width="1114" alt="Image" src="https://github.com/user-attachments/assets/81b9e02d-60a4-4e7d-8fc0-209277593b0e" />

### Logs

<details>
<summary>See logs</summary>

```
##[group]Run phips28/gh-action-bump-version@master
with:
  commit-message: CI: bumps version to {{version}} [skip ci]
  default: minor
  minor-wording: feat,minor
  major-wording: BREAKING CHANGE,major
  rc-wording: pre-alpha,pre-beta,pre-rc
  skip-tag: false
  skip-commit: false
  skip-push: false
  preid: rc
  bump-policy: all
  check-last-commit-only: false
  custom-git-domain: github.com
  commit-no-verify: false
  push: true
env:
  GITHUB_TOKEN: ***
  PACKAGEJSON_DIR: packages/editor
##[endgroup]
process.env.GITHUB_WORKSPACE /home/runner/work/xxx/xxx/packages/editor
tagPrefix: 
tagSuffix: 
commit messages: [ '[TMP] Test version bump 3\nundefined' ]
config words: {
  majorWords: [ 'BREAKING CHANGE', 'major' ],
  minorWords: [ 'feat', 'minor' ],
  patchWords: null,
  preReleaseWords: [ 'pre-alpha', 'pre-beta', 'pre-rc' ]
}
version action after first waterfall: minor
version action after final decision: minor
runInWorkspace | command: git args: [ 'config', 'user.name', '"Automated Version Bump"' ]
runInWorkspace | command: git args: [
  'config',
  'user.email',
  '"gh-action-bump-version@users.noreply.github.com"'
]
currentBranch: dev
runInWorkspace | command: npm args: [ 'config', 'set', 'fund', 'false', '-ws=false', '-iwr' ]
runInWorkspace | command: npm args: [
  'version',
  '--allow-same-version=true',
  '--git-tag-version=false',
  '1.193.0'
]
current 1: 1.193.0 / version: minor
[parseNpmVersionOutput] output: v1.194.0

[parseNpmVersionOutput] npmVersionStr: v1.194.0
newVersion 1: 1.194.0
runInWorkspace | command: git args: [ 'commit', '-a', '-m', 'CI: bumps version to 1.194.0 [skip ci]' ]
runInWorkspace | command: git args: [ 'checkout', 'dev' ]
runInWorkspace | command: npm args: [
  'version',
  '--allow-same-version=true',
  '--git-tag-version=false',
  '1.193.0'
]
current 2: 1.193.0 / version: minor
execute npm version now with the new version: minor
[parseNpmVersionOutput] output: v1.194.0

[parseNpmVersionOutput] npmVersionStr: v1.194.0
newVersion 2: 1.194.0
newVersion after merging tagPrefix+newVersion+tagSuffix: 1.194.0
runInWorkspace | command: sh args: [ '-c', 'echo "newTag=1.194.0" >> $GITHUB_OUTPUT' ]
runInWorkspace | command: git args: [ 'commit', '-a', '-m', 'CI: bumps version to 1.194.0 [skip ci]' ]
runInWorkspace | command: git args: [ 'tag', '1.194.0' ]
runInWorkspace | command: git args: [
  'push',
  '***github.com/xxx/xxx.git',
  '--follow-tags'
]
✖  fatal     remote: error: GH013: Repository rule violations found for refs/heads/dev.        
remote: Review all repository rules at https://github.com/xxx/xxx/rules?ref=refs%2Fheads%2Fdev        
remote: 
remote: - Changes must be made through a pull request.        
remote: 
To https://github.com/xxx/xxx.git
 ! [remote rejected] dev -> dev (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/xxx/xxx.git'

git exited with code 1
✖  fatal     Failed to bump version
Post job cleanup.
```

</details>
