### ISSUE TITLE
NullPointer when triggered by branch close

### ISSUE THREAD

**Issue by dschoon** [phips28/gh-action-bump-version#30]
Hello, thanks for making this plugin!
I'm running into a nullpointer, and I think it may be due to the fact that my github action runs when the pull request is closed and merged to master.

```
Couldn't find any commits in this event, incrementing patch version...
✖  fatal     TypeError: Cannot read property '1' of null 
    at /index.js:42:79
```
**index.js**
```
    const currentBranch = /refs\/[a-zA-Z]+\/(.*)/.exec(process.env.GITHUB_REF)[1]
    console.log('currentBranch:', currentBranch)
```

The problem I have is my github action also publishes to NPM, so I don't really want to publish every time a branch is opened. Do you have a recommended workaround for this? Is this just not a valid usecase?

**Comment by phips28** [comment]
can you share your config file?

this action does not publish to npm, do you have an other action for that?

**Comment by NeonWizard** [comment]
I'm getting this same problem. Here is my configuration:
```yaml
name: Bump NPM Package Version

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

jobs:
  version:
    name: Version
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          token: REDACTED

      - uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: REDACTED
        with:
          target-branch: 'develop'
          skip-tag: true
          # only increment patch version (default)
          # regardless of commit history
          minor-wording: ''
          major-wording: ''
          patch-wording: ''
          rc-wording: ''
```

**Comment by phips28** [comment]
Can you spot the error? maybe you can provide a fix via PR. I am currently limited in time to debug this issue :(

**Comment by NeonWizard** [comment]
> Can you spot the error? maybe you can provide a fix via PR. I am currently limited in time to debug this issue :(

I'll see if I can take a peek sometime within the next week. For now, I managed to get the desired behavior with this temporary workaround:

```yaml
name: Bump NPM Package Version

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  version:
    name: Version
    if: ${{ startsWith(github.event.head_commit.message, 'Merge pull request') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          token: REDACTED

      - uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: REDACTED
        with:
          target-branch: 'develop'
          skip-tag: true
          # only increment patch version (default)
          # regardless of commit history
          minor-wording: 'SOME UNIQUE STRING THAT WILL NEVER BE USED HOPEFULLY'
          major-wording: 'SOME UNIQUE STRING THAT WILL NEVER BE USED HOPEFULLY'
          rc-wording: 'SOME UNIQUE STRING THAT WILL NEVER BE USED HOPEFULLY'
```
