### ISSUE TITLE
Error: Command failed: git checkout 15/merge 

### ISSUE THREAD

**Issue by devo-wm** [phips28/gh-action-bump-version#33]
```
/usr/bin/docker run --name b3ac637fe3f33d1de420baf5e0923fe2f117b_ffa6d8 --label 3b3ac6 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_TAG-PREFIX -e INPUT_PACKAGEJSON_DIR -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/headless-react/headless-react":"/github/workspace" 3b3ac6:37fe3f33d1de420baf5e0923fe2f117b
6
Couldn't find any commits in this event, incrementing patch version...
7
currentBranch: 15/merge
8
current: 0.1.0 / version: patch
9
✖  fatal     Error: Command failed: git checkout 15/merge 
10
error: pathspec '15/merge' did not match any file(s) known to git.
```

Keep getting the above when trying to run testing out this action on the yaml below

```yaml
# This is a basic workflow to help you get started with Actions

name: Bump Version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ adds_build_scripts ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bump-version:
    name: Automated Version Bump
    runs-on: ubuntu-latest
      steps:
        - name: "Checkout source code"
          uses: "actions/checkout@v2"
          with:
            ref: ${{ github.ref }}
        - name: "cat package.json"
          run: cat ./package.json
        - name: "Setup Node.js"
          uses: "actions/setup-node@v1"
          with:
            node-version: 12
        - name: "Automated Version Bump"
          uses: "phips28/gh-action-bump-version@master"
          with:
            tag-prefix: ''
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: "cat package.json"
          run: cat ./package.json
  
```

**Comment by phips28** [comment]
> currentBranch: 15/merge

hmm I never had a branch starting with a number. Have you tried it on a non-numeric branch name?

**Comment by devo-wm** [comment]
I have no idea where that's coming from I was merging a branch auto-version-test into another called adds_build_scripts

**Comment by mitchdowney** [comment]
I've just run into this issue when trying to use this action. Could the number represent the PR number? In my case this is PR #1...

```
Couldn't find any commits in this event, incrementing patch version...
currentBranch: 1/merge
current: 1.0.0 / version: patch
✖  fatal     Error: Command failed: git checkout 1/merge 
error: pathspec '1/merge' did not match any file(s) known to git.
```

https://github.com/podverse/user-agents/pull/1/checks?check_run_id=1050329086

And here is the action file:

```
name: master-branch

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: "Automated Version Bump"
      uses: "phips28/gh-action-bump-version@master"
      with:
        tag-prefix: ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ...
```
