### ISSUE TITLE
v8.0.2 Fails on git fetch

### ISSUE THREAD

**Issue by sambernard** [phips28/gh-action-bump-version#40]
The latest version seems to be failing for me when it tries to call git fetch.

Here are the related steps from my actions.yml:
```
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY_FOR_SUBMODULES }}
      - name: Bump Version
        if: ${{ success() }}
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

And here is the output from github:
```
Run phips28/gh-action-bump-version@master
  with:
    minor-wording: feat,minor
    major-wording: BREAKING CHANGE,major
    skip-tag: false
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    GITHUB_TOKEN: ***
/usr/bin/docker run --name aac2aac10c58df17bd46f38e0c76dd7c62d5ff_c44c18 --label aac2aa --workdir /github/workspace --rm -e NPM_CONFIG_USERCONFIG -e NODE_AUTH_TOKEN -e GITHUB_TOKEN -e INPUT_TAG-PREFIX -e INPUT_MINOR-WORDING -e INPUT_MAJOR-WORDING -e INPUT_SKIP-TAG -e INPUT_PACKAGEJSON_DIR -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/api/api":"/github/workspace" aac2aa:c10c58df17bd46f38e0c76dd7c62d5ff
currentBranch: master
current: 0.0.11 / version: patch
✖  fatal     Error: Command failed: git fetch 
Warning: Identity file /home/runner/work/_temp/10d8eec1-fe29-44c9-a9b9-13c0d69a9bfe not accessible: No such file or directory.
No RSA host key is known for github.com and you have requested strict checking.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


    at makeError (/node_modules/execa/index.js:174:9)
    at /node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /index.js:59:5
✖  fatal     Failed to bump version
```
