### ISSUE TITLE
Protected branch

### ISSUE THREAD

**Issue by johanlajili** [phips28/gh-action-bump-version#62]
Hi, I'm trying to use this action in a repo configured with a protected main branch that requires 1 PR review.

When using this action, it fails because it tries to commit to main directly. I've tried using an alternative github token, one created with my own admin account, as I've read over the internet it would work, but it does not seem to have any impact.

Here is how i'm using the action

```yaml

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
    paths-ignore:
        - 'package.json'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Increase version number
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
        uses: phips28/gh-action-bump-version@v8.0.12
```

and ACTION_GITHUB_TOKEN is defined in the secret of the repository based on my own user account.

**Comment by johanlajili** [comment]
Actually resolved the issue using the github token on the checkout action as well:
```yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
    paths-ignore:
        - 'package.json'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
        with:  
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}
      
      - name: Increase version number
        uses: phips28/gh-action-bump-version@v8.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
        
```
