### ISSUE TITLE
target-branch fails

### ISSUE THREAD

**Issue by nbilyk** [phips28/gh-action-bump-version#70]
I might be doing something wrong, but if I set the target-branch property, I get the following:

```
✖  fatal     Error: Command failed: git checkout development 
error: pathspec 'development' did not match any file(s) known to git.


    at makeError (/node_modules/execa/index.js:174:9)
    at /node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /index.js:99:5
```

My yml:

```
name: Publish release
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: "Publish on NPMJS"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm ci
          npm run test
          npm run doc
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Deploy JS Docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: jsdocs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: jsdocs
          COMMIT_MESSAGE: 'Update docs'
  # https://github.com/phips28/gh-action-bump-version/blob/master/.github/workflows/push.yml
  bump-version:
    name: "Bump version on master"
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: "Automated version bump"
        id: version-bump
        uses: phips28/gh-action-bump-version@v8.0.18
        with:
          tag-prefix: ""
          target-branch: "development"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Echo new tag"
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

```

**Comment by HendricksonTyler** [comment]
@nbilyk Did you find a solution to this? I'm running into the same problem

**Comment by melody-universe** [comment]
@HendricksonTyler I was running into the same problem while building a test suite for this action. It turns out `target-branch` needs to exist on the runner. You need to either fetch the branch (if it already exists) or create it in a step prior to running this action.

It's arguable it this action should probably create `target-branch` if it doesn't already exist.

```yaml
      name: Bump Version (Target Branch)
      on:
        push:
          branches:
            - main
      jobs:
        bump-version:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2

            - run: git branch other-branch
            # **OR**
            - run: git fetch origin other-branch

            - id: version-bump
              uses: phips28/gh-action-bump-version@v8.0.18
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                target-branch: other-branch
```
