### ISSUE TITLE
Auto Clone and auto branch

### ISSUE THREAD

**Issue by AlphaNiner1415** [phips28/gh-action-bump-version#71]
So I was wondering, by default does this action auto-clone my github repo? cuz I'm noticing quite a spike of clones after I've added this action. Not sure if that's the case just asking. Also the ci is automatically branching master sometimes and not branching on others, and sometimes it takes multiple commits before a new version is pushed out (I have it set to on push to master) any idea how to fix that?

**Comment by phips28** [comment]
this action does not clone your repo.
check my action file how I set it up:
https://github.com/phips28/gh-action-bump-version/blob/master/.github/workflows/push.yml

**Comment by AlphaNiner1415** [comment]
Hmmmm Ok so the problem here is that per one commit, the workflow is incrementing my version twice, is there a way to fix that?

**Comment by AlphaNiner1415** [comment]
<img width="388" alt="Screen Shot 2021-01-26 at 17 27 21" src="https://user-images.githubusercontent.com/39154768/105833531-e6e30600-5ffb-11eb-911a-ca049d5bfc3f.png">

here's what I'm talking about, the top two commits you see on the list in the picture above is the work flow 

Below is the code for my workflow

```
name: "Bump Version"

#Based on the commit messages, increment the version from the latest release.
   #If the string "BREAKING CHANGE", "major" or the Attention pattern refactor!: drop support for Node 6 is found anywhere in any of the commit messages or descriptions the major version will be incremented.
   #If a commit message begins with the string "feat" or includes "minor" then the minor version will be increased. This works for most common commit metadata for feature additions: "feat: new API" and "feature: new API".
   #If a commit message contains the word "pre-alpha" or "pre-beta" or "pre-rc" then the pre-release version will be increased (for example specifying pre-alpha: 1.6.0-alpha.1 -> 1.6.0-alpha.2 or, specifying pre-beta: 1.6.0-alpha.1 -> 1.6.0-beta.0)
    ##All other changes will increment the patch version.
#Push the bumped npm version in package.json back into the repo.
#Push a tag for the new version back into the repo.

on:
  push:
    branches:
      - "master"

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12
      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "cat package.json"
        run: cat ./package.json
      - name:  'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
```
