### ISSUE TITLE
tag-prefix input being ignored

### ISSUE THREAD

**Issue by vodlogic** [phips28/gh-action-bump-version#84]
Hello!

When using the following config or omitting the tag-prefix option so the default applies, the tag is created with a 'v' prefix on the version number.

```
- name: 'Bump Version'
  id: bump_version
  uses: 'phips28/gh-action-bump-version@v8.2.2'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
  with:
    skip-tag: 'true'
    tag-prefix: ''
    target-branch: 'main'
    commit-message: 'CI: Bump version to {{version}} [skip ci]'
    major-wording: 'MAJOR,cut-major,major:'
    minor-wording: 'add,Adds,new,feat, feat:'
    rc-wording: 'RELEASE,alpha'`
```

Looking at the code, this seems to be added when executing

```
npm version --git-tag-version=false --allow-same-version=true 0.0.36
v0.0.36
```

I think the 'v' should be stripped off from output of this command so that the version number is normalised before adding the tag-prefix.

I also noticed that the commitMessageRegex replace on the {{version}} contains the v prefix too so this should become optional
