### ISSUE TITLE
'commit-message' input not working

### ISSUE THREAD

**Issue by steakeye-gitlive-test** [phips28/gh-action-bump-version#88]
Using the current latest version `phips28/gh-action-bump-version@v8.0.18`, I get the following message in CI:
```
Warning: Unexpected input(s) 'commit-message', valid inputs are ['entryPoint', 'args', 'tag-prefix', 'minor-wording', 'major-wording', 'patch-wording', 'rc-wording', 'skip-tag', 'PACKAGEJSON_DIR', 'target-branch', 'default']
```
And unfortunately that means I can't customise the commit message to include `[skip ci]`, which is useful if you want to avoid repeating the CI pipeline after you push into the same branch.

The workaround has been to use:
```
    if: ${{ !startsWith(github.event.head_commit.message, 'ci:') }}
```
but this is more maintenance hassle than I'd like as the `if` condition has to be set on every step, whereas a `[skip ci]` string would allow CI to ignore the commit entirely.

**Comment by Steakeye** [comment]
Commenting with my main account so I can get updates!

**Comment by CWSites** [comment]
I have the following config and it works just fine. Perhaps the version you are using is out of date?

```
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
```
