### ISSUE TITLE
Question: Action not respecting trigger words

### ISSUE THREAD

**Issue by CWSites** [phips28/gh-action-bump-version#90]
My config is below, recently I had the action run with a commit message `add dispatch for release, breakout build to separate step\nundefined` which doesn't include my wording of `MAJOR, minor, patch, alpha`. My suspicion is that it was because of the word `release` however I would like to understand why that caused it to trigger if I explicitly do not have that word being watched.

What words are being watched by this action and how do I overwrite them properly? I need to make sure we don't have any accidental bumps.

```yml
      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PACKAGEJSON_DIR: 'libs/dot-components'
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          default: prerelease
          major-wording: 'MAJOR'
          minor-wording: 'minor'
          patch-wording: 'patch'
          rc-wording: 'alpha'
          target-branch: 'master'
          # rc-wording will override the preid
          preid: 'alpha'
```
