### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by milkboxpontus** [phips28/gh-action-bump-version#91]
Hey!

When the gh-action-bump-version step runs and push to the GitHub repo, it will trigger a new run on the pipeline.
That will lead to a infinite loop, until i cancel the current running pipeline.

Any ideas?

![image](https://user-images.githubusercontent.com/78731590/117428272-35bb0880-af26-11eb-8ba7-74a44aa707a1.png)

**Comment by CWSites** [comment]
I have my workflow to only run on specific files being modified.

```yml
on:
  push:
    paths:
      - .github/workflows/version.yml
      - CHANGE_LOG.md
      - libs/my-app/src/**
    branches:
      - master
```
