### ISSUE TITLE
git commit failed `actions/checkout@v2`?

### ISSUE THREAD

**Issue by CWSites** [phips28/gh-action-bump-version#94]
I'm getting the following message in my action output on GitHub. The workflow shows that it is successful but if that's the case why is this showing?

```
git commit failed because you are using "actions/checkout@v2"; but that doesnt matter because you dont need that git commit, thats only for "actions/checkout@v1"
```

## Workflow Config
```yml
  bump-version:
    name: Bump Version & Create GitHub Tag
    runs-on: ubuntu-latest
    needs: [checks]
    outputs:
      new-version: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PACKAGEJSON_DIR: 'libs/dot-components'
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          default: prerelease
          major-wording: 'MAJOR'
          minor-wording: 'minor'
          # Providing patch-wording will override commits defaulting to a patch bump.
          # patch-wording: 'patch'
          rc-wording: 'alpha, RELEASE, BETA'
          target-branch: 'master'
          # rc-wording will override the preid
          preid: 'alpha'

      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
```
