### ISSUE TITLE
`package.json` version doesn't update with `tag-prefix`

### ISSUE THREAD

**Issue by CWSites** [phips28/gh-action-bump-version#95]
I've just run into the issue which I have `tag-prefix: 'alpha-'` and it is NOT being added to `package.json`? It's working on the GitHub Tag itself but not `package.json`.

## Action Config
```
  bump-version:
    name: Bump Version & Create GitHub Tag
    runs-on: ubuntu-latest
    needs: [checks]
    outputs:
      new-version: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PACKAGEJSON_DIR: 'libs/dot-components'
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          major-wording: 'MAJOR'
          minor-wording: 'MINOR'
          target-branch: 'master'
          preid: 'alpha'
          tag-prefix: 'alpha-'
```

_Originally posted by @CWSites in https://github.com/phips28/gh-action-bump-version/issues/84#issuecomment-845375209_
