### ISSUE TITLE
Tagging missing "v" in front of version number

### ISSUE THREAD

**Issue by dpvball** [phips28/gh-action-bump-version#99]
so this started a couple days ago. The v is missing in front of the tag for the version number. I'm currently pointed at your master branch for the action. it's now resulting in this output when the action is run and doesn't show the updated "new version"
```
currentBranch: master
current: 2.1.47 / version: patch
current: 2.1.47 / version: patch
git commit failed because you are using "actions/checkout@v2"; but that doesnt matter because you dont need that git commit, thats only for "actions/checkout@v1"
✔  success   Version bumped!
```

Even though it shows Version Bumped, Previously this would be the output.
```
currentBranch: master
current: 2.1.46 / version: patch
current: 2.1.46 / version: patch
new version: v2.1.47
git commit failed because you are using "actions/checkout@v2"; but that doesnt matter because you dont need that git commit, thats only for "actions/checkout@v1"
✔  success   Version bumped!
```

The tag created is now 2.1.47 rather than v2.1.47. I rolled back to gh-action-bump-version@v8.2.2 and it is working again as expected.

**Comment by phips28** [comment]
Hi. Sorry for that. 
you need to use the tag-prefix in later versions to explicitly set this:

```
- name: "Automated Version Bump"
      - id: version-bump
      - uses: "phips28/gh-action-bump-version@master"        
      with:
          tag-prefix: 'v'
```
